.TH MSWORLD 1 "August 2025" "msworld 1.0.0" "User Commands"
.SH NAME
msworld \- Magic Scripts example greeting command
.SH SYNOPSIS
.B msworld
[\fIOPTION\fR]...
[\fINAME\fR]
.SH DESCRIPTION
msworld is a simple example Magic Scripts command that demonstrates configuration usage and basic command structure.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help message
.TP
.B \-v, \-\-version
Show version information
.SH CONFIGURATION
Uses Magic Scripts configuration system:
.TP
.B AUTHOR_NAME
Name to use in greeting
.SH EXAMPLES
.TP
.B msworld
Basic greeting
.TP
.B msworld Alice
Greet Alice
.SH AUTHOR
Magic Scripts development team
.SH SEE ALSO
.BR ms (1)